# Generated by Django 4.2.3 on 2023-07-12 17:44

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TurbineData",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("temperature", models.IntegerField()),
                ("exhaust_mass", models.IntegerField()),
                ("fuel_consumed", models.IntegerField()),
                ("rotations_per_second", models.IntegerField()),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
